In [ ]:
# 02

import pandas as pd

raw_data ={'first_name' : ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'],
           'last_name' : ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze'],
           'age' : [42, 52, 36, 24, 73]}

df = pd.DataFrame(raw_data, index=['a', 'b', 'c', 'd', 'e'])
df["a"] # 열 조회 실패

KeyError: 'a'

In [ ]:
# 04

import pandas as pd
nested_dict = {'Korea' : {2019: 4.6, 2020: 5.7, 2021: 4.8},
               'Japan' : {2020: 1.5, 2020: 1.5, 2021: 1.6}}

df = pd.DataFrame(nested_dict).T
df

# 2019의 값이 없기에 NaN으로 표시된다.

       2019  2020  2021
Korea   4.6   5.7   4.8
Japan   NaN   1.5   1.6

In [ ]:
# 05

import pandas as pd

data = [['Choi', 29], ['Kim', 32], ['Jung', 27], ['Lee', 25]]
df = pd.DataFrame(data, columns=['Name', 'Age'], index=[1, 2, 3, 4])

df.iloc[2]['Age']

# iloc[2]로 3번째 행을 선택한 뒤, 'Age' 열의 값을 조회한다. iloc는 위치 기반 인덱싱이므로, 2는 3번째 행을 의미한다. 따라서, df.iloc[2]['Age']는 27을 반환한다.

np.int64(27)

In [ ]:
import pandas as pd

ipl_data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings',
                     'kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
            'Rank': [1, 2, 2, 3, 3, 4, 1, 1, 2, 4, 1, 2],
            'Year': [2014, 2015, 2014, 2015, 2014, 2015, 2016, 2017, 2016, 2014, 2015, 2017],
            'Points': [876, 789, 863, 673, 741, 812, 756, 788, 694, 701, 804, 690]}

df = pd.DataFrame(ipl_data)
df.groupby("Team")["Points"].mean()

# Team 열을 기준으로 그룹화한 뒤, 각 그룹의 Points 열의 평균값을 계산한다. 결과적으로 각 팀별로 평균 점수를 반환한다.

Team
Devils    768.000000
Kings     761.666667
Riders    762.250000
Royals    752.500000
kings     812.000000
Name: Points, dtype: float64

In [ ]:
# 08

import pandas as pd

data = [['Choi', 29], ['Kim', 32], ['Jung', 27], ['Lee', 25]]
df = pd.DataFrame(data, columns=['Name', 'Age'], index=[1, 2, 3, 4])

#df.drop('Age', axis=1)
#del df['Age']
df.drop('Age', axis=1, inplace=True) 
#df = df[["Name"]]

df

# inplace true를 사용하면 원본에서 Age열이 삭제된다.

   Name
1  Choi
2   Kim
3  Jung
4   Lee

In [14]:
# 12

import numpy as np
import pandas as pd

df = pd.DataFrame(np.arange(1, 17).reshape(4, 4))
df


(df + df.mean(axis=1)) ** 2
#(df + df.mean(axis=9)) ** 2
#(df + df.rows()) ** 2
#df.mean(axis=1).sum() ** 2

        0       1       2       3
0   12.25   72.25  182.25  342.25
1   56.25  156.25  306.25  506.25
2  132.25  272.25  462.25  702.25
3  240.25  420.25  650.25  930.25